import MarkdownContent from "@/components/Common/MarkdownContent";
import styles from "../../RepositoryDetail.module.css";
import CollapsibleSection from "../CollapsibleSection";

function SummarySection({ summary, expanded, onToggle }) {
  if (!summary) return null;

  return (
    <CollapsibleSection
      section="summary"
      title="Summary"
      expanded={expanded}
      onToggle={onToggle}
      badge={
        summary.ai_generated ? (
          <span className={styles.badgeAi}>✨ AI Generated</span>
        ) : null
      }
    >
      <div className={styles.sectionContent}>
        <MarkdownContent
          content={summary.text}
          className={styles.summaryText}
        />
        {summary.model_used && (
          <div className={styles.textMuted}>
            Generated by {summary.model_used}
            {summary.confidence_score && (
              <> • Confidence: {summary.confidence_score}%</>
            )}
          </div>
        )}
      </div>
    </CollapsibleSection>
  );
}

export default SummarySection;
