import MarkdownContent from "@/components/Common/MarkdownContent";
import styles from "../../RepositoryDetail.module.css";
import CollapsibleSection from "../CollapsibleSection";

function SummarySection({ summary, expanded, onToggle }) {
  if (!summary || !summary.summary) return null;

  return (
    <CollapsibleSection
      section="summary"
      title="AI Summary"
      expanded={expanded}
      onToggle={onToggle}
      badge={<span className={styles.badgeAi}>✨ AI</span>}
    >
      <div className={styles.sectionContent}>
        <MarkdownContent
          content={summary.summary}
          className={styles.summaryText}
        />

        {summary.purpose && (
          <p style={{ marginTop: "0.75rem", fontSize: "0.875rem" }}>
            <strong>Purpose:</strong> {summary.purpose}
          </p>
        )}

        {summary.tech_highlights && summary.tech_highlights.length > 0 && (
          <div style={{ marginTop: "0.5rem" }}>
            <span
              style={{
                fontSize: "0.7rem",
                textTransform: "uppercase",
                letterSpacing: "0.05em",
                fontWeight: 600,
                color: "var(--color-text-muted)",
              }}
            >
              Tech stack:
            </span>{" "}
            {summary.tech_highlights.map((t) => (
              <span
                key={t}
                className={styles.badge}
                style={{ marginRight: "4px", fontSize: "0.75rem" }}
              >
                {t}
              </span>
            ))}
          </div>
        )}

        {summary.project_maturity && (
          <div style={{ marginTop: "0.5rem" }}>
            <span
              style={{
                fontSize: "0.7rem",
                textTransform: "uppercase",
                letterSpacing: "0.05em",
                fontWeight: 600,
                color: "var(--color-text-muted)",
              }}
            >
              Maturity:
            </span>{" "}
            <span className={styles.badge}>
              {summary.project_maturity.replace(/-/g, " ")}
            </span>
          </div>
        )}

        {summary.model && (
          <div
            className={styles.textMuted}
            style={{ marginTop: "0.75rem", fontSize: "0.75rem" }}
          >
            Generated by {summary.model}
            {summary.generated_at && (
              <>
                {" "}
                &middot; {new Date(summary.generated_at).toLocaleDateString()}
              </>
            )}
          </div>
        )}
      </div>
    </CollapsibleSection>
  );
}

export default SummarySection;
