source 'https://rubygems.org'

ruby '3.2.0'

gem 'rails', '~> 7.0.5'
gem 'pg', '~> 1.5'
gem 'puma', '~> 6.3'
gem 'redis', '~> 5.0'
gem 'sidekiq', '~> 7.1'

group :development, :test do
  gem 'rspec-rails', '~> 6.0'
  gem 'factory_bot_rails', '~> 6.2'
  gem 'faker', '~> 3.2'
end

group :development do
  gem 'rubocop', '~> 1.52', require: false
  gem 'rubocop-rails', '~> 2.20', require: false
end
