"""Report entity model for complete analysis output."""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Dict, List, Optional

from spark.models.profile import UserProfile
from spark.models.repository import Repository
from spark.models.summary import RepositorySummary
from spark.models.commit import CommitHistory
from spark.models.tech_stack import TechnologyStack


@dataclass
class RepositoryAnalysis:
    """Complete analysis data for a single repository.

    Combines repository metadata, commit history, tech stack, and summary.

    Attributes:
        repository: Repository metadata and stats
        commit_history: Commit patterns and temporal data
        tech_stack: Technology and dependency information
        summary: AI-generated or fallback summary
        rank: Position in the top N ranking (1-based)
        composite_score: Final ranking score (0-100)
    """

    repository: Repository
    commit_history: Optional[CommitHistory] = None
    tech_stack: Optional[TechnologyStack] = None
    summary: Optional[RepositorySummary] = None
    rank: int = 0
    composite_score: float = 0.0

    def to_dict(self) -> dict:
        """Serialize repository analysis to dictionary."""
        return {
            "repository": self.repository.to_dict(),
            "commit_history": self.commit_history.to_dict() if self.commit_history else None,
            "tech_stack": self.tech_stack.to_dict() if self.tech_stack else None,
            "summary": self.summary.to_dict() if self.summary else None,
            "rank": self.rank,
            "composite_score": self.composite_score,
        }


@dataclass
class Report:
    """Complete repository analysis report for a GitHub user.

    This is the top-level entity that aggregates all analysis results,
    including user profile, repository analyses, and generation metadata.

    Attributes:
        username: GitHub username analyzed
        user_profile: Overall developer profile and patterns
        repositories: List of RepositoryAnalysis objects (ranked)
        generation_timestamp: When report was generated
        metadata: Additional report metadata (version, config, stats)
        errors: List of errors encountered during generation
        partial_results: Whether report is incomplete due to failures
        total_api_calls: Total GitHub API calls made
        total_ai_tokens: Total AI model tokens consumed
        generation_time_seconds: Time taken to generate report
    """

    username: str
    user_profile: Optional[UserProfile] = None
    repositories: List[RepositoryAnalysis] = field(default_factory=list)
    generation_timestamp: datetime = field(default_factory=datetime.now)
    metadata: Dict[str, any] = field(default_factory=dict)
    errors: List[str] = field(default_factory=list)
    partial_results: bool = False
    total_api_calls: int = 0
    total_ai_tokens: int = 0
    generation_time_seconds: float = 0.0

    def __post_init__(self):
        """Initialize default metadata if not provided."""
        if not self.metadata:
            self.metadata = {
                "stats_spark_version": "1.0.0",
                "report_type": "repository_analysis",
                "top_n": len(self.repositories),
                "ai_summaries_count": sum(1 for ra in self.repositories if ra.summary and ra.summary.is_ai_generated),
                "fallback_summaries_count": sum(
                    1 for ra in self.repositories if ra.summary and not ra.summary.is_ai_generated
                ),
            }

    def add_repository_analysis(self, analysis: RepositoryAnalysis) -> None:
        """Add a repository analysis to the report.

        Args:
            analysis: RepositoryAnalysis instance to add
        """
        self.repositories.append(analysis)
        # Update metadata
        self.metadata["top_n"] = len(self.repositories)

    def add_error(self, error: str) -> None:
        """Add an error message to the report.

        Args:
            error: Error description
        """
        self.errors.append(error)
        self.partial_results = True

    @property
    def success_rate(self) -> float:
        """Calculate percentage of successful repository analyses.

        Returns:
            Percentage (0-100) of repositories successfully analyzed
        """
        if not self.repositories:
            return 0.0
        successful = sum(1 for ra in self.repositories if ra.summary is not None)
        return round((successful / len(self.repositories)) * 100, 1)

    @property
    def ai_summary_rate(self) -> float:
        """Calculate percentage of AI-generated summaries.

        Returns:
            Percentage (0-100) of summaries generated by AI
        """
        if not self.repositories:
            return 0.0
        ai_summaries = sum(1 for ra in self.repositories if ra.summary and ra.summary.is_ai_generated)
        return round((ai_summaries / len(self.repositories)) * 100, 1)

    @property
    def total_repositories_analyzed(self) -> int:
        """Get total count of repositories in report.

        Returns:
            Number of repositories
        """
        return len(self.repositories)

    def to_dict(self) -> dict:
        """Serialize report to dictionary format.

        Returns:
            Dictionary with all report fields
        """
        return {
            "username": self.username,
            "user_profile": self.user_profile.to_dict() if self.user_profile else None,
            "repositories": [ra.to_dict() for ra in self.repositories],
            "generation_timestamp": self.generation_timestamp.isoformat(),
            "metadata": self.metadata,
            "errors": self.errors,
            "partial_results": self.partial_results,
            "total_api_calls": self.total_api_calls,
            "total_ai_tokens": self.total_ai_tokens,
            "generation_time_seconds": self.generation_time_seconds,
            "success_rate": self.success_rate,
            "ai_summary_rate": self.ai_summary_rate,
            "total_repositories_analyzed": self.total_repositories_analyzed,
        }
